**Q1**

In [1]:
import numpy as np

In [2]:
arr = np.array([2,5,6,35,6,786,32,35])

In [3]:
arr+2

array([  4,   7,   8,  37,   8, 788,  34,  37])

In [4]:
arr*3

array([   6,   15,   18,  105,   18, 2358,   96,  105])

In [5]:
arr/2

array([  1. ,   2.5,   3. ,  17.5,   3. , 393. ,  16. ,  17.5])

**Q2**

a)

In [6]:
 arr = np.array([1, 2, 3, 6, 4, 5])
revarr = arr[::-1]

In [7]:
revarr

array([5, 4, 6, 3, 2, 1])

b)

**Q3**

In [8]:
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [9]:
arr[0,2]

np.int64(30)

In [10]:
arr[2,0]

np.int64(70)

**Q4**

In [11]:
dev = np.linspace(10,100,25)

In [12]:
dev

array([ 10.  ,  13.75,  17.5 ,  21.25,  25.  ,  28.75,  32.5 ,  36.25,
        40.  ,  43.75,  47.5 ,  51.25,  55.  ,  58.75,  62.5 ,  66.25,
        70.  ,  73.75,  77.5 ,  81.25,  85.  ,  88.75,  92.5 ,  96.25,
       100.  ])

In [13]:
dev.shape

(25,)

In [14]:
dev.size

25

In [15]:
dev.dtype

dtype('float64')

In [16]:
dev.nbytes

200

In [17]:
transpose = dev.reshape(25,1).T

In [18]:
transpose

array([[ 10.  ,  13.75,  17.5 ,  21.25,  25.  ,  28.75,  32.5 ,  36.25,
         40.  ,  43.75,  47.5 ,  51.25,  55.  ,  58.75,  62.5 ,  66.25,
         70.  ,  73.75,  77.5 ,  81.25,  85.  ,  88.75,  92.5 ,  96.25,
        100.  ]])

In [19]:
transpose2 = dev.T
transpose2

array([ 10.  ,  13.75,  17.5 ,  21.25,  25.  ,  28.75,  32.5 ,  36.25,
        40.  ,  43.75,  47.5 ,  51.25,  55.  ,  58.75,  62.5 ,  66.25,
        70.  ,  73.75,  77.5 ,  81.25,  85.  ,  88.75,  92.5 ,  96.25,
       100.  ])

**Q5**

In [20]:
x = [10,20,30,40,50,60, 70, 80, 90, 15, 20, 35]

In [21]:
ucs420_dev = np.array(x)
ucs420_dev

array([10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35])

In [22]:
ucs420_dev = ucs420_dev.reshape(3,4)

In [23]:
ucs420_dev

array([[10, 20, 30, 40],
       [50, 60, 70, 80],
       [90, 15, 20, 35]])

In [24]:
np.mean(ucs420_dev)

np.float64(43.333333333333336)

In [25]:
np.max(ucs420_dev)

np.int64(90)

In [26]:
np.median(ucs420_dev)

np.float64(37.5)

In [27]:
np.min(ucs420_dev)

np.int64(10)

In [28]:
np.unique(ucs420_dev)

array([10, 15, 20, 30, 35, 40, 50, 60, 70, 80, 90])

In [29]:
reshaped_ucs420_dev = ucs420_dev.reshape(4,3)

In [30]:
reshaped_ucs420_dev

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90],
       [15, 20, 35]])

In [32]:
resize_ucs420_dev = np.resize(ucs420_dev,(2,3))

In [33]:
resize_ucs420_dev

array([[10, 20, 30],
       [40, 50, 60]])